# Generated by Django 5.2.8 on 2026-08-29 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MusicTrack",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("track_id", models.CharField(max_length=30)),
                ("artist", models.CharField(max_length=100)),
                ("album", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("preview_url", models.CharField(max_length=100)),
                (
                    "song_image",
                    models.ImageField(blank=True, upload_to="spotify_images"),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("track_id", "user")},
            },
        ),
    ]
