# Generated by Django 5.2.8 on 2026-08-29 15:38

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(max_length=3, unique=True)),
                ("usd_exchange_rate", models.CharField(default="1.0", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="CurrencyHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency_date", models.DateField()),
                (
                    "usd_exchange_rate_low",
                    models.CharField(default="1.0", max_length=20),
                ),
                (
                    "usd_exchange_rate_high",
                    models.CharField(default="1.0", max_length=20),
                ),
                ("usd_exchange_rate", models.CharField(default="1.0", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="stock.currency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exchange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mic", models.CharField(max_length=5, unique=True)),
                ("ric", models.CharField(default=None, max_length=5)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("acronym", models.CharField(max_length=15, unique=True)),
                ("country_code", models.CharField(max_length=5)),
                ("city", models.CharField(max_length=20)),
                ("website", models.CharField(max_length=50)),
                ("timezone", models.CharField(max_length=30)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchanges",
                        to="stock.currency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20, unique=True)),
                ("symbol_ric", models.CharField(max_length=20, unique=True)),
                ("company", models.CharField(max_length=75)),
                (
                    "type",
                    models.CharField(
                        blank=True, default=None, max_length=10, null=True
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stock.currency"
                    ),
                ),
                (
                    "exchange",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="stock.exchange",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_trading_time", models.DateTimeField()),
                ("open", models.CharField(default=0.0, max_length=20)),
                ("latest_price", models.CharField(default=0.0, max_length=20)),
                ("day_low", models.CharField(default=0.0, max_length=20)),
                ("day_high", models.CharField(default=0.0, max_length=20)),
                ("volume", models.CharField(default=0.0, max_length=20)),
                ("close_yesterday", models.CharField(default=0.0, max_length=20)),
                ("change_pct", models.CharField(default=0.0, max_length=20)),
                ("day_change", models.CharField(default=0.0, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="stock.stock",
                    ),
                ),
            ],
            options={
                "unique_together": {("stock", "last_trading_time")},
            },
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("portfolio_name", models.CharField(max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolios",
                        to="stock.person",
                    ),
                ),
            ],
            options={
                "unique_together": {("portfolio_name", "user")},
            },
        ),
        migrations.CreateModel(
            name="PortfolioHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trading_date", models.DateField()),
                ("quantity", models.CharField(default=0.0, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="stock.portfolio",
                    ),
                ),
                (
                    "stock_history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock.stockhistory",
                    ),
                ),
            ],
            options={
                "unique_together": {("portfolio", "stock_history")},
            },
        ),
        migrations.CreateModel(
            name="StockSelection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.CharField(default=0.0, max_length=20)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="stock.portfolio",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="stock.stock"
                    ),
                ),
            ],
            options={
                "unique_together": {("stock", "portfolio")},
            },
        ),
    ]
