# Generated by Django 3.0.7 on 2020-11-23 05:42

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='exchange',
            old_name='exchange_short',
            new_name='acronym',
        ),
        migrations.RenameField(
            model_name='exchange',
            old_name='time_zone_name',
            new_name='timezone',
        ),
        migrations.RenameField(
            model_name='exchange',
            old_name='exchange_long',
            new_name='website',
        ),
        migrations.AddField(
            model_name='exchange',
            name='city',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchange',
            name='country_code',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchange',
            name='currency',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='stock.Currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchange',
            name='mic',
            field=models.CharField(default='', max_length=5, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchange',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchange',
            name='ric',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='stock',
            name='symbol_ric',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Currency'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Exchange'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='stock.Person'),
        ),
    ]
