# Generated by Django 4.1.4 on 2023-08-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="type",
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
