# Generated by Django 4.1.4 on 2023-08-27 09:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0002_stock_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="type",
        ),
    ]
