# Customised stock lists

stock_lists = {'AEX': ['AALB.AS',
                       'ABN.AS',
                       'ADYEN.AS',
                       'AGN.AS',
                       'AD.AS',
                       'AKZA.AS',
                       'MT.AS',
                       'ASML.AS',
                       'ASRNL.AS',
                       'DSM.AS',
                       'GLPG.AS',
                       'HEIA.AS',
                       'IMCD.AS',
                       'INGA.AS',
                       'KPN.AS',
                       'NN.AS',
                       'PHIA.AS',
                       'RAND.AS',
                       'REN.AS',
                       'RDSA.AS',
                       'TKWY.AS',
                       'URW.PA',
                       'UNA.AS',
                       'VPK.AS',
                       'WKL.AS',
                       ],

               'TECH': ['AAPL',
                        'ADYEN.AS',
                        'AMZN',
                        'ASML.AS',
                        'FB',
                        'GOOG',
                        'HPE',
                        'IBM',
                        'INTC',
                        'MSFT',
                        'ORCL',
                        'PHIA.AS',
                        'TSLA',
                        '005930.KS',
                        ],

               'DOW': ['AXP',
                       'AAPL',
                       'BA',
                       'CAT',
                       'CSCO',
                       'CVX',
                       'XOM',
                       'GS',
                       'HD',
                       'IBM',
                       'INTC',
                       'JNJ',
                       'KO',
                       'JPM',
                       'MCD',
                       'MMM',
                       'MRK',
                       'MSFT',
                       'NKE',
                       'PFE',
                       'PG',
                       'TRV',
                       'UNH',
                       'UTX',
                       'VZ',
                       'V',
                       'WBA',
                       'WMT',
                       'DIS',
                       'DOW',
                      ],
               }
