# Stock list of markets

indexes = {'AEX': ['AALB.AS',
                   'ABN.AS',
                   'ADYEN.AS',
                   'AGN.AS',
                   'AD.AS',
                   'AKZA.AS',
                   'MT.AS',
                   'ASML.AS',
                   'ASRNL.AS',
                   'DSM.AS',
                   'GLPG.AS',
                   'HEIA.AS',
                   'IMCD.AS',
                   'INGA.AS',
                   'KPN.AS',
                   'NN.AS',
                   'PHIA.AS',
                   'RAND.AS',
                   'REN.AS',
                   'RDSA.AS',
                   'TKWY.AS',
                   'URW.PA',
                   'UNA.AS',
                   'VPK.AS',
                   'WKL.AS',
                   ],
}
