# Generated by Django 5.2.8 on 2026-08-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Home",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("welcome_text", models.TextField(max_length=2000)),
                ("welcome_image", models.ImageField(null=True, upload_to="images/")),
                ("member_text", models.TextField(max_length=2000)),
                ("member_image", models.ImageField(null=True, upload_to="images/")),
            ],
        ),
        migrations.CreateModel(
            name="Signup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
