# common values
MESSAGE_FIELD_SIZE = 8000
BOARD_NAME_SIZE = 30
DESCRIPTION_SIZE = 100
TOPIC_SUBJECT_SIZE = 255
POSTS_PER_PAGE = 2
TOPICS_PER_PAGE = 10
HAS_MANY_PAGES_LIMIT = 3
POST_SUBJECT_SIZE = 255
EXCLUDE_USERS = ['default_user', 'moderator']
MAX_SYMBOLS_ALLOWED = 20
UPDATE_INTERVAL = 21600
BASE_CURRENCIES = [('EUR', 'EUR'), ('USD', 'USD')]
RIGHT_ARROW = '\u25B6'
LEFT_ARROW = '\u25C0'
