# Generated by Django 2.2 on 2019-04-27 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_site', models.CharField(max_length=15, unique=True)),
                ('news_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UserNewsSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_sites', models.ManyToManyField(to='newsfeed.NewsSite')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserNewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=400)),
                ('summary', models.TextField(max_length=4000)),
                ('link', models.URLField()),
                ('published', models.DateTimeField(null=True)),
                ('news_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsfeed.NewsSite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
