# Generated by Django 3.0.7 on 2020-11-23 05:42

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message',
            field=martor.models.MartorField(help_text='Maximum length is 20000 characters', max_length=20000),
        ),
    ]
